name: RDC

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch: 

jobs:
  create-random-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Create random commits
        run: |
          #!/bin/bash
          
          make_commit() {
            echo $RANDOM >> random_file.txt
            git add random_file.txt
            git commit -m "Random commit $1"
          }
          
          num_commits=$((RANDOM % 6 + 5))
          
          for i in $(seq 1 $num_commits)
          do
            sleep $((RANDOM % 7200))
            make_commit $i
          done
          
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Random failure
        if: ${{ random(100) < 20 }} 
        run: exit 1
