name: Python
on:
  schedule:
     - cron: '0 10,12,16,20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check repo content
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: execute python script
      run: |
        python main.py
    - name: Commit files
      run: |
        git config --local user.email "wekesa360@outlook.com"
        git config --local user.name "wekesa360"
        git add .
        git commit -m "Update file" -a

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.G_TOKEN }}
        branch: main