name: Tetris Commit Pattern

on:
  schedule:
    - cron: '0 10,12,16,20 * * 1-5'

jobs:
  commit-pattern:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script
      run: |
        python main.py

    - name: Commit changes
      run: |
        git config --global user.name 'wekesa360'
        git config --global user.email 'wekesa360@outlook.com'
        git add commit.txt
        git commit -m "Tetris commit pattern on $(date +'%Y-%m-%d')"
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.G_TOKEN }}
        branch: main